version: "3.5"

services:
  nginx:
    restart: always

    build:
      context: ./nginx
      dockerfile: Dockerfile

    ports:
      - 8081:8081

    depends_on:
      - flask-app

    networks:
      - flask_app_network

  flask-app:
    image: alekcoraglez/flask-app:latest
    # image: gcr.io/gcp-platform-test-x/flask-app:latest
    container_name: flask-app
    restart: always

    command: flask run --host=0.0.0.0

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/flask-app

    environment:
      - FLASK_APP=/flask-app/manage.py
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

    ports:
      - 5000:5000

    networks:
      - flask_app_network

    depends_on:
      - postgres


  postgres:
    container_name: postgres
    image: postgres:12
    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_project

    volumes:
      - ./docker/volumes/db:/var/lib/postgresql/data

    ports:
      - 5435:5432

    networks:
      - flask_app_network


networks:
  flask_app_network:
    driver: bridge
